apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.1
          command: [ "/opt/keycloak/bin/kc.sh" ,"start-dev", "--import-realm", "--hostname-strict=false", "--hostname-strict-https=false"]
          env:
            - name: DB_VENDOR
              value: "MYSQL"
            - name: DB_ADDR
              value: "keycloak-mysql"
            - name: DB_DATABASE
              value: "keycloak"
            - name: DB_USER
              value: "keycloak"
            - name: DB_PASSWORD
              value: "password"
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: keycloak-realms
              mountPath: /opt/keycloak/data/import/
      volumes:
        - name: keycloak-realms
          hostPath:
            path: /home/azureuser/spring-boot-3-microservices-course/k8s/manifests/infra/keycloak/docker/keycloak/realms  # Change to your host absolute path
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080          # Service port (for internal cluster access)
      targetPort: 8080    # Pod/container port
      nodePort: 32222     # External port on each node

